name: "Multi-Provider Code Review"
description: "Hybrid AST + LLM code review with multiple providers"
author: "Keith Herrington"
branding:
  icon: "code-review"
  color: "blue"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  PR_NUMBER:
    description: "Pull request number"
    required: true
  REVIEW_PROVIDERS:
    description: "Comma-separated provider list"
    required: false
    default: "openrouter/google/gemini-2.0-flash-exp:free,openrouter/mistralai/devstral-2512:free"
  FALLBACK_PROVIDERS:
    description: "Comma-separated fallback providers"
    required: false
    default: ""
  SYNTHESIS_MODEL:
    description: "Model used for synthesis/prompts"
    required: false
    default: "openrouter/google/gemini-2.0-flash-exp:free"
  INLINE_MAX_COMMENTS:
    description: "Maximum inline comments"
    required: false
    default: "5"
  INLINE_MIN_SEVERITY:
    description: "Minimum severity for inline comments"
    required: false
    default: "major"
  INLINE_MIN_AGREEMENT:
    description: "Providers required to agree"
    required: false
    default: "2"
  MIN_CHANGED_LINES:
    description: "Skip if below this line count"
    required: false
    default: "0"
  MAX_CHANGED_FILES:
    description: "Skip if over this file count"
    required: false
    default: "0"
  SKIP_LABELS:
    description: "Comma-separated labels to skip"
    required: false
    default: ""
  PROVIDER_LIMIT:
    description: "Limit number of providers to rotate"
    required: false
    default: "6"
  PROVIDER_RETRIES:
    description: "Retries per provider"
    required: false
    default: "2"
  PROVIDER_MAX_PARALLEL:
    description: "Maximum providers to run in parallel"
    required: false
    default: "3"
  DIFF_MAX_BYTES:
    description: "Maximum diff bytes to send to providers"
    required: false
    default: "120000"
  RUN_TIMEOUT_SECONDS:
    description: "Timeout per provider run"
    required: false
    default: "600"
  BUDGET_MAX_USD:
    description: "Budget guard in USD"
    required: false
    default: "0"
  ENABLE_AST_ANALYSIS:
    description: "Enable AST analysis"
    required: false
    default: "true"
  ENABLE_SECURITY:
    description: "Enable security scan"
    required: false
    default: "true"
  ENABLE_CACHING:
    description: "Enable caching of findings"
    required: false
    default: "true"
  ENABLE_TEST_HINTS:
    description: "Enable test coverage hints"
    required: false
    default: "true"
  ENABLE_AI_DETECTION:
    description: "Enable AI-generated code detection"
    required: false
    default: "true"
  REPORT_BASENAME:
    description: "Base name for JSON/SARIF reports"
    required: false
    default: "multi-provider-review"
  DRY_RUN:
    description: "Preview mode - run review without posting to GitHub"
    required: false
    default: "false"
  OPENROUTER_API_KEY:
    description: "API key for OpenRouter"
    required: false

outputs:
  findings_count:
    description: "Number of findings"
  critical_count:
    description: "Critical findings count"
  cost_usd:
    description: "Total cost in USD"
  total_cost:
    description: "Total cost in USD (alias for cost_usd)"
  ai_likelihood:
    description: "Average AI-generated likelihood"

runs:
  using: "node20"
  main: "dist/index.js"
