name: "Multi-Provider Code Review"
description: "Run code reviews with multiple providers using OpenCode"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  REVIEW_PROVIDERS:
    description: "Comma-separated list of review providers"
    required: false
    default: "opencode/big-pickle,opencode/grok-code,opencode/minimax-m2.1-free,opencode/glm-4.7-free"
  PR_TITLE:
    description: "PR title"
    required: true
  PR_NUMBER:
    description: "PR number"
    required: true
  PR_BODY:
    description: "PR body"
    required: true
  HAS_AGENTS:
    description: "Whether AGENTS.md exists"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run Multi-Provider Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REVIEW_PROVIDERS: ${{ inputs.REVIEW_PROVIDERS }}
        PR_TITLE: ${{ inputs.PR_TITLE }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
        PR_BODY: ${{ inputs.PR_BODY }}
        HAS_AGENTS: ${{ inputs.HAS_AGENTS }}
      run: |
        # Copy agent configs
        mkdir -p .opencode/agent

        cat > .opencode/agent/big-pickle-reviewer.md << 'EOF'
        ---
        description: Big Pickle code reviewer
        mode: subagent
        model: opencode/big-pickle
        temperature: 0.1
        tools:
          write: false
          edit: false
        permission:
          bash:
            "gh pr comment*": allow
            "gh api*": allow
        ---
        You are a code reviewer using Big Pickle model. Focus on:
        - Code quality and best practices
        - Security vulnerabilities and risks
        - Performance issues and optimization opportunities
        - Testing gaps and edge cases
        - Architectural concerns

        Provide constructive feedback with specific line numbers and actionable suggestions. Only comment on actual issues.
        EOF

        cat > .opencode/agent/grok-code-reviewer.md << 'EOF'
        ---
        description: Grok Code reviewer
        mode: subagent
        model: opencode/grok-code
        temperature: 0.1
        tools:
          write: false
          edit: false
        permission:
          bash:
            "gh pr comment*": allow
            "gh api*": allow
        ---
        You are a code reviewer using Grok Code model. Focus on:
        - Code quality and best practices
        - Security vulnerabilities and risks
        - Performance issues and optimization opportunities
        - Testing gaps and edge cases
        - Architectural concerns

        Provide constructive feedback with specific line numbers and actionable suggestions. Only comment on actual issues.
        EOF

        cat > .opencode/agent/minimax-reviewer.md << 'EOF'
        ---
        description: Minimax code reviewer
        mode: subagent
        model: opencode/minimax-m2.1-free
        temperature: 0.1
        tools:
          write: false
          edit: false
        permission:
          bash:
            "gh pr comment*": allow
            "gh api*": allow
        ---
        You are a code reviewer using Minimax model. Focus on:
        - Code quality and best practices
        - Security vulnerabilities and risks
        - Performance issues and optimization opportunities
        - Testing gaps and edge cases
        - Architectural concerns

        Provide constructive feedback with specific line numbers and actionable suggestions. Only comment on actual issues.
        EOF

        cat > .opencode/agent/glm-reviewer.md << 'EOF'
        ---
        description: GLM-4.7 code reviewer
        mode: subagent
        model: opencode/glm-4.7-free
        temperature: 0.1
        tools:
          write: false
          edit: false
        permission:
          bash:
            "gh pr comment*": allow
            "gh api*": allow
        ---
        You are a code reviewer using GLM-4.7 model. Focus on:
        - Code quality and best practices
        - Security vulnerabilities and risks
        - Performance issues and optimization opportunities
        - Testing gaps and edge cases
        - Architectural concerns

        Provide constructive feedback with specific line numbers and actionable suggestions. Only comment on actual issues.
        EOF

        # Build review prompt
        AGENTS_CONTENT=""
        if [ "$HAS_AGENTS" = "true" ] && [ -f "AGENTS.md" ]; then
          AGENTS_CONTENT=$(head -c 2000 AGENTS.md)
          AGENTS_SECTION=$'\n\n## Project Guidelines (from AGENTS.md)\n'"$AGENTS_CONTENT"
        fi

        cat > /tmp/review-prompt.txt << 'PROMPT_EOF'
        REPO: ${{ github.repository }}
        PR NUMBER: ${{ inputs.PR_NUMBER }}
        PR TITLE: ${{ inputs.PR_TITLE }}
        PR DESCRIPTION:
        ${{ inputs.PR_BODY }}

        Please review this pull request and provide comprehensive code review focusing on:

        ## Code Quality & Best Practices
        - Clean code principles and readability
        - Proper error handling and edge cases
        - TypeScript/JavaScript best practices
        - Consistent naming conventions

        ## Bug Detection
        - Logic errors and edge cases
        - Unhandled error scenarios
        - Race conditions and concurrency issues
        - Input validation and sanitization

        ## Performance
        - Inefficient algorithms or operations
        - Memory leaks and unnecessary allocations
        - Large file handling

        ## Security
        - SQL injection, XSS, CSRF vulnerabilities
        - Authentication/authorization issues
        - Sensitive data exposure

        ## Testing
        - Test coverage gaps
        - Missing edge case handling${AGENTS_SECTION}

        ## Output Format
        - Use \`gh pr comment\` to leave review comments on specific files
        - Include specific line numbers and code suggestions
        - Provide actionable recommendations
        - Summarize key findings at end

        IMPORTANT: Only create comments for actual issues. If the code follows all guidelines, respond with 'lgtm' only.
        PROMPT_EOF

        # Read modified files
        gh api /repos/${{ github.repository }}/pulls/${{ inputs.PR_NUMBER }}/files > /tmp/pr-files.json

        # Get diff
        git diff --name-status > /tmp/changed-files.txt

        echo "========================================"
        echo "Running multi-provider code review"
        echo "========================================"
        echo "Review prompt: $(wc -l < /tmp/review-prompt.txt)"
        echo "Modified files: $(wc -l < /tmp/changed-files.txt)"
        echo ""

        # Run opencode with Task tool to invoke all review subagents in parallel
        echo "Launching parallel reviews..."
        opencode run "@big-pickle-reviewer @grok-code-reviewer @minimax-reviewer @glm-reviewer Review the code changes for this PR using the review criteria in /tmp/review-prompt.txt. After all reviews complete, synthesize the results into one comprehensive review and post as a PR comment using gh CLI."

branding:
  icon: "code-review"
  color: "blue"
