name: "Multi-Provider Code Review"
description: "Run code reviews with multiple providers using OpenCode"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  REVIEW_PROVIDERS:
    description: "Comma-separated list of review providers"
    required: false
    default: "opencode/big-pickle,opencode/grok-code,opencode/minimax-m2.1-free,opencode/glm-4.7-free"
  PR_TITLE:
    description: "PR title"
    required: true
  PR_NUMBER:
    description: "PR number"
    required: true
  PR_BODY:
    description: "PR body"
    required: true
  HAS_AGENTS:
    description: "Whether AGENTS.md exists"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run Multi-Provider Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REVIEW_PROVIDERS: ${{ inputs.REVIEW_PROVIDERS }}
        PR_TITLE: ${{ inputs.PR_TITLE }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
        PR_BODY: ${{ inputs.PR_BODY }}
        HAS_AGENTS: ${{ inputs.HAS_AGENTS }}
      run: |
        set -euo pipefail

        if ! command -v npm >/dev/null 2>&1; then
          echo "npm is required but not found on PATH."
          exit 1
        fi

        if ! command -v opencode >/dev/null 2>&1; then
          echo "opencode CLI not found; installing via npm (opencode-ai)..."
          NPM_PREFIX="${NPM_PREFIX:-$HOME/.npm-global}"
          mkdir -p "$NPM_PREFIX"
          npm config set prefix "$NPM_PREFIX"
          export PATH="$NPM_PREFIX/bin:$PATH"
          npm install -g opencode-ai@latest
        fi

        if ! command -v opencode >/dev/null 2>&1; then
          echo "opencode CLI is required but not found in PATH. Please install it before running this action."
          exit 1
        fi

        if ! command -v gh >/dev/null 2>&1; then
          echo "GitHub CLI (gh) is required but not found in PATH."
          exit 1
        fi

        export GH_TOKEN="${GITHUB_TOKEN}"

        IFS=',' read -ra PROVIDERS <<< "$REVIEW_PROVIDERS"
        if [ "${#PROVIDERS[@]}" -eq 0 ]; then
          echo "No review providers found. REVIEW_PROVIDERS was empty."
          exit 1
        fi

        REPO="${GITHUB_REPOSITORY:-}"
        if [ -z "$REPO" ]; then
          echo "GITHUB_REPOSITORY is not set; unable to determine repository."
          exit 1
        fi

        SYNTHESIS_MODEL="${SYNTHESIS_MODEL:-opencode/big-pickle}"
        DIFF_MAX_BYTES="${DIFF_MAX_BYTES:-120000}"

        PR_TITLE_VALUE="${PR_TITLE}"
        PR_BODY_VALUE="${PR_BODY}"

        AGENTS_SECTION=""
        if [ "${HAS_AGENTS}" = "true" ] && [ -f "AGENTS.md" ]; then
          AGENTS_CONTENT=$(head -c 2000 AGENTS.md)
          AGENTS_SECTION=$'\n\n## Project Guidelines (from AGENTS.md)\n'"${AGENTS_CONTENT}"
        fi

        gh api "/repos/${REPO}/pulls/${PR_NUMBER}/files" > /tmp/pr-files.json || true
        DIFF_FILE="/tmp/pr.diff"
        if gh api "/repos/${REPO}/pulls/${PR_NUMBER}" -H "Accept: application/vnd.github.v3.diff" > "$DIFF_FILE"; then
          DIFF_SIZE=$(wc -c < "$DIFF_FILE")
          if [ "$DIFF_SIZE" -gt "$DIFF_MAX_BYTES" ]; then
            echo "Diff is ${DIFF_SIZE} bytes, truncating to ${DIFF_MAX_BYTES}."
            head -c "$DIFF_MAX_BYTES" "$DIFF_FILE" > "${DIFF_FILE}.tmp"
            echo $'\n\n[Diff truncated for length]' >> "${DIFF_FILE}.tmp"
            mv "${DIFF_FILE}.tmp" "$DIFF_FILE"
          fi
        else
          echo "Warning: Unable to fetch PR diff via gh api."
          DIFF_FILE=""
        fi

        cat > /tmp/review-prompt.txt <<EOF
        REPO: ${REPO}
        PR NUMBER: ${PR_NUMBER}
        PR TITLE: ${PR_TITLE_VALUE}
        PR DESCRIPTION:
        ${PR_BODY_VALUE}

        Please review this pull request and provide a comprehensive code review focusing on:

        ## Code Quality & Best Practices
        - Clean code principles and readability
        - Proper error handling and edge cases
        - TypeScript/JavaScript best practices
        - Consistent naming conventions

        ## Bug Detection
        - Logic errors and edge cases
        - Unhandled error scenarios
        - Race conditions and concurrency issues
        - Input validation and sanitization

        ## Performance
        - Inefficient algorithms or operations
        - Memory leaks and unnecessary allocations
        - Large file handling

        ## Security
        - SQL injection, XSS, CSRF vulnerabilities
        - Authentication/authorization issues
        - Sensitive data exposure

        ## Testing
        - Test coverage gaps
        - Missing edge case handling${AGENTS_SECTION}

        ## Output Format
        - Provide specific file and line numbers when possible
        - Include code suggestions in fenced code blocks
        - Summarize key findings and risks at the end

        IMPORTANT: Only flag actual issues. If everything looks good, respond with 'lgtm'.
        EOF

        if [ -s /tmp/pr-files.json ]; then
          echo $'\n\n## Changed Files' >> /tmp/review-prompt.txt
          if command -v jq >/dev/null 2>&1; then
            jq -r '.[] | "- " + .filename + " (+" + (.additions|tostring) + "/-" + (.deletions|tostring) + ")"' /tmp/pr-files.json >> /tmp/review-prompt.txt
          else
            python - <<'PYCODE' /tmp/pr-files.json >> /tmp/review-prompt.txt || true
import json, sys
try:
    files = json.load(open(sys.argv[1]))
    for f in files:
        additions = f.get("additions", 0)
        deletions = f.get("deletions", 0)
        print(f"- {f.get('filename', 'unknown')} (+{additions}/-{deletions})")
except Exception:
    pass
PYCODE
          fi
        fi

        if [ -n "${DIFF_FILE}" ] && [ -f "${DIFF_FILE}" ]; then
          echo $'\n\n## Diff' >> /tmp/review-prompt.txt
          cat "${DIFF_FILE}" >> /tmp/review-prompt.txt
        fi

        PROMPT_CONTENT="$(cat /tmp/review-prompt.txt)"

        echo "========================================"
        echo "Running multi-provider code review"
        echo "========================================"
        echo "Review prompt size: $(wc -c < /tmp/review-prompt.txt) bytes"
        echo "Providers: ${PROVIDERS[*]}"
        echo "Synthesis model: ${SYNTHESIS_MODEL}"
        echo ""

        mkdir -p /tmp/reviews
        PROVIDER_LIST=()
        for raw_provider in "${PROVIDERS[@]}"; do
          provider="$(echo "$raw_provider" | xargs)"
          [ -z "$provider" ] && continue
          PROVIDER_LIST+=("$provider")
          outfile="/tmp/reviews/$(echo "$provider" | tr '/:' '__').txt"
          echo "Running provider: ${provider}"
          if opencode run -m "${provider}" -- "${PROMPT_CONTENT}" > "$outfile" 2> "${outfile}.log"; then
            echo "âœ… ${provider} completed"
          else
            echo "âš ï¸ ${provider} failed (see log), capturing partial output"
            echo "Provider ${provider} failed. Log:" > "$outfile"
            cat "${outfile}.log" >> "$outfile" || true
          fi
        done

        if [ "${#PROVIDER_LIST[@]}" -eq 0 ]; then
          echo "No valid providers ran successfully."
          exit 1
        fi

        SYN_PROMPT=/tmp/synthesis-prompt.txt
        echo "Synthesizing results with ${SYNTHESIS_MODEL}"
        cat > "$SYN_PROMPT" <<'SYN_HEAD'
        You are an expert code reviewer. Combine the provider reviews below into a single, concise GitHub PR review.

        Requirements:
        - Merge overlapping feedback; avoid duplicate points.
        - Highlight unique insights from each provider.
        - Include file and line references when present.
        - Provide code suggestions in fenced blocks where applicable.
        - Keep output under GitHub's comment limits.

        Output structure:
        1) Summary (bullet list)
        2) Findings (grouped by severity: Critical, Major, Minor)
        3) Recommendations / tests to run
        4) Verdict (Approve, Approve with recommendations, or Request changes)

        Provider reviews:
SYN_HEAD

        for provider in "${PROVIDER_LIST[@]}"; do
          fname="/tmp/reviews/$(echo "$provider" | tr '/:' '__').txt"
          {
            echo ""
            echo "### ${provider}"
            echo ""
            cat "$fname"
            echo ""
            echo "---"
          } >> "$SYN_PROMPT"
        done

        SYNTHESIS_OUTPUT=/tmp/synthesis.txt
        if opencode run -m "${SYNTHESIS_MODEL}" -- "$(cat "$SYN_PROMPT")" > "$SYNTHESIS_OUTPUT" 2> /tmp/synthesis.log; then
          echo "âœ… Synthesis complete"
        else
          echo "âš ï¸ Synthesis failed, using concatenated provider outputs"
          cat "$SYN_PROMPT" > "$SYNTHESIS_OUTPUT"
        fi

        COMMENT_FILE=/tmp/final-review.md
        {
          echo "ðŸ¤– **Multi-Provider Code Review**"
          echo ""
          echo "**Providers:** ${PROVIDER_LIST[*]}"
          echo "**Synthesis model:** ${SYNTHESIS_MODEL}"
          echo ""
          cat "$SYNTHESIS_OUTPUT"
          echo ""
          echo "<details><summary>Raw provider outputs</summary>"
          echo ""
          for provider in "${PROVIDER_LIST[@]}"; do
            fname="/tmp/reviews/$(echo "$provider" | tr '/:' '__').txt"
            echo ""
            echo "#### ${provider}"
            echo ""
            cat "$fname"
          done
          echo ""
          echo "</details>"
        } > "$COMMENT_FILE"

        gh api --method POST -H "Accept: application/vnd.github+json" "/repos/${REPO}/issues/${PR_NUMBER}/comments" -F body="@${COMMENT_FILE}"

        echo ""
        echo "âœ… Review posted to PR #${PR_NUMBER}"

branding:
  icon: "code-review"
  color: "blue"
