name: "Multi-Provider Code Review"
description: "Run code reviews with multiple providers using OpenCode"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  REVIEW_PROVIDERS:
    description: "Comma-separated list of review providers"
    required: false
    default: "opencode/big-pickle,opencode/grok-code,opencode/minimax-m2.1-free,opencode/glm-4.7-free"
  PR_TITLE:
    description: "PR title"
    required: true
  PR_NUMBER:
    description: "PR number"
    required: true
  PR_BODY:
    description: "PR body"
    required: true
  HAS_AGENTS:
    description: "Whether AGENTS.md exists"
    required: false
    default: "false"
  SYNTHESIS_MODEL:
    description: "Model used to synthesize provider outputs"
    required: false
    default: "opencode/big-pickle"
  DIFF_MAX_BYTES:
    description: "Maximum diff bytes to include in prompt"
    required: false
    default: "120000"

runs:
  using: "composite"
  steps:
    - name: Run Multi-Provider Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REVIEW_PROVIDERS: ${{ inputs.REVIEW_PROVIDERS }}
        PR_TITLE: ${{ inputs.PR_TITLE }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
        PR_BODY: ${{ inputs.PR_BODY }}
        HAS_AGENTS: ${{ inputs.HAS_AGENTS }}
        SYNTHESIS_MODEL: ${{ inputs.SYNTHESIS_MODEL }}
        DIFF_MAX_BYTES: ${{ inputs.DIFF_MAX_BYTES }}
      run: bash "${{ github.action_path }}/action.sh"

branding:
  icon: "code-review"
  color: "blue"
