import { MetricsCollector, MetricsData, ReviewMetric } from './metrics-collector';
import { logger } from '../utils/logger';
import * as fs from 'fs/promises';

// Type definitions for dashboard data
interface CostTrend {
  date: string;
  cost: number;
  reviews: number;
}

interface PerformanceTrend {
  date: string;
  avgDuration: number;
}

interface ROIData {
  totalCost: number;
  estimatedTimeSaved: number;
  estimatedTimeSavedValue: number;
  roi: number;
}

/**
 * Generates an HTML analytics dashboard with charts and statistics
 */
export class DashboardGenerator {
  constructor(private readonly metricsCollector: MetricsCollector) {}

  /**
   * Escape HTML special characters to prevent XSS
   */
  private escapeHtml(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    };
    return text.replace(/[&<>"']/g, (char) => map[char]);
  }

  /**
   * Generate complete HTML dashboard
   */
  async generateDashboard(): Promise<string> {
    logger.info('Generating analytics dashboard');

    const stats = await this.metricsCollector.getStats();
    const costTrends = await this.metricsCollector.getCostTrends(30);
    const perfTrends = await this.metricsCollector.getPerformanceTrends(30);
    const roi = await this.metricsCollector.calculateROI();

    const html = this.buildHTML(stats, costTrends, perfTrends, roi);

    logger.info('Dashboard generated successfully');
    return html;
  }

  /**
   * Save dashboard to file
   */
  async saveDashboard(filepath: string): Promise<void> {
    const html = await this.generateDashboard();
    await fs.writeFile(filepath, html, 'utf8');
    logger.info(`Dashboard saved to ${filepath}`);
  }

  /**
   * Export metrics as CSV
   */
  async exportCSV(): Promise<string> {
    const metrics = await this.metricsCollector.getMetrics();

    const headers = [
      'Timestamp',
      'PR Number',
      'Files Reviewed',
      'Findings',
      'Cost (USD)',
      'Duration (s)',
      'Providers Used',
      'Cache Hit',
    ];

    const rows = metrics.map((m) => [
      new Date(m.timestamp).toISOString(),
      m.prNumber.toString(),
      m.filesReviewed.toString(),
      m.findingsCount.toString(),
      m.costUsd.toFixed(4),
      m.durationSeconds.toFixed(2),
      m.providersUsed.toString(),
      m.cacheHit ? 'Yes' : 'No',
    ]);

    // Escape and join CSV rows
    const csv = [
      headers.map(h => this.escapeCSVField(h)).join(','),
      ...rows.map((r) => r.map(f => this.escapeCSVField(f)).join(','))
    ].join('\n');

    return csv;
  }

  /**
   * Escape a CSV field value to handle commas, quotes, and newlines
   */
  private escapeCSVField(value: string): string {
    // If the value contains comma, quote, or newline, wrap in quotes and escape internal quotes
    if (value.includes(',') || value.includes('"') || value.includes('\n') || value.includes('\r')) {
      return `"${value.replace(/"/g, '""')}"`;
    }
    return value;
  }

  /**
   * Save CSV export to file
   */
  async saveCSV(filepath: string): Promise<void> {
    const csv = await this.exportCSV();
    await fs.writeFile(filepath, csv, 'utf8');
    logger.info(`CSV exported to ${filepath}`);
  }

  /**
   * Build complete HTML document
   */
  private buildHTML(stats: MetricsData, costTrends: CostTrend[], perfTrends: PerformanceTrend[], roi: ROIData): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Multi-Provider Code Review Analytics</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
  <style>
    ${this.getCSS()}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>📊 Multi-Provider Code Review Analytics</h1>
      <p class="subtitle">Dashboard generated on ${this.escapeHtml(new Date().toLocaleString())}</p>
    </header>

    ${this.buildSummaryCards(stats, roi)}

    <div class="charts-grid">
      ${this.buildCostTrendChart(costTrends)}
      ${this.buildPerformanceTrendChart(perfTrends)}
      ${this.buildFindingsDistributionChart(stats)}
      ${this.buildProviderSuccessChart(stats)}
    </div>

    ${this.buildROISection(roi)}
    ${this.buildRecentReviewsTable(stats.reviews)}

    <footer>
      <p>Generated by Multi-Provider Code Review v2.1</p>
      <p>🤖 <a href="https://github.com/keithah/multi-provider-code-review">View on GitHub</a></p>
    </footer>
  </div>

  <script>
    ${this.getChartJS(costTrends, perfTrends, stats)}
  </script>
</body>
</html>`;
  }

  /**
   * Build summary cards HTML
   */
  private buildSummaryCards(stats: MetricsData, roi: ROIData): string {
    return `
    <div class="summary-cards">
      <div class="card">
        <div class="card-icon">📝</div>
        <div class="card-content">
          <h3>Total Reviews</h3>
          <p class="card-value">${stats.totalReviews}</p>
        </div>
      </div>

      <div class="card">
        <div class="card-icon">💰</div>
        <div class="card-content">
          <h3>Total Cost</h3>
          <p class="card-value">$${stats.totalCost.toFixed(2)}</p>
        </div>
      </div>

      <div class="card">
        <div class="card-icon">🐛</div>
        <div class="card-content">
          <h3>Total Findings</h3>
          <p class="card-value">${stats.totalFindings}</p>
        </div>
      </div>

      <div class="card">
        <div class="card-icon">⚡</div>
        <div class="card-content">
          <h3>Avg Review Time</h3>
          <p class="card-value">${stats.avgReviewTime.toFixed(1)}s</p>
        </div>
      </div>

      <div class="card">
        <div class="card-icon">📈</div>
        <div class="card-content">
          <h3>Cache Hit Rate</h3>
          <p class="card-value">${stats.cacheHitRate.toFixed(1)}%</p>
        </div>
      </div>

      <div class="card highlight">
        <div class="card-icon">💎</div>
        <div class="card-content">
          <h3>ROI</h3>
          <p class="card-value">${roi.roi.toFixed(0)}%</p>
          <p class="card-subtitle">$${roi.estimatedTimeSavedValue.toFixed(0)} value</p>
        </div>
      </div>
    </div>`;
  }

  /**
   * Build cost trend chart HTML
   */
  private buildCostTrendChart(_costTrends: CostTrend[]): string {
    return `
    <div class="chart-container">
      <h2>💰 Cost Trends (Last 30 Days)</h2>
      <canvas id="costTrendChart"></canvas>
    </div>`;
  }

  /**
   * Build performance trend chart HTML
   */
  private buildPerformanceTrendChart(_perfTrends: PerformanceTrend[]): string {
    return `
    <div class="chart-container">
      <h2>⚡ Review Performance (Last 30 Days)</h2>
      <canvas id="perfTrendChart"></canvas>
    </div>`;
  }

  /**
   * Build findings distribution chart HTML
   *
   * NOTE: Severity breakdown is not currently tracked in ReviewMetric.
   * To implement this feature, ReviewMetric would need additional fields:
   * criticalCount, majorCount, minorCount. This would require updating
   * the MetricsCollector.recordReview() method to aggregate findings by severity.
   *
   * For now, the chart shows placeholder data. Tracked in issue #TODO
   */
  private buildFindingsDistributionChart(_stats: MetricsData): string {
    return `
    <div class="chart-container">
      <h2>🐛 Findings by Severity</h2>
      <canvas id="findingsChart"></canvas>
      <p class="chart-note">Placeholder chart - severity tracking not yet implemented</p>
    </div>`;
  }

  /**
   * Build provider success chart HTML
   */
  private buildProviderSuccessChart(_stats: MetricsData): string {
    return `
    <div class="chart-container">
      <h2>🤖 Provider Success Rate</h2>
      <canvas id="providerChart"></canvas>
    </div>`;
  }

  /**
   * Build ROI section HTML
   */
  private buildROISection(roi: ROIData): string {
    return `
    <div class="roi-section">
      <h2>💎 Return on Investment Analysis</h2>
      <div class="roi-grid">
        <div class="roi-item">
          <h3>Total Cost</h3>
          <p class="roi-value">$${roi.totalCost.toFixed(2)}</p>
          <p class="roi-desc">Actual spending on LLM providers</p>
        </div>
        <div class="roi-item">
          <h3>Time Saved</h3>
          <p class="roi-value">${(roi.estimatedTimeSaved / 60).toFixed(1)} hours</p>
          <p class="roi-desc">Based on 30min manual review per PR</p>
        </div>
        <div class="roi-item">
          <h3>Value Generated</h3>
          <p class="roi-value">$${roi.estimatedTimeSavedValue.toFixed(2)}</p>
          <p class="roi-desc">At $100/hour developer rate</p>
        </div>
        <div class="roi-item highlight">
          <h3>Net ROI</h3>
          <p class="roi-value">${roi.roi.toFixed(0)}%</p>
          <p class="roi-desc">Return on investment</p>
        </div>
      </div>
    </div>`;
  }

  /**
   * Build recent reviews table HTML
   */
  private buildRecentReviewsTable(reviews: ReviewMetric[]): string {
    const recent = reviews.slice(-10).reverse(); // Last 10, newest first

    const rows = recent
      .map(
        (r: ReviewMetric) => `
      <tr>
        <td>${this.escapeHtml(new Date(r.timestamp).toLocaleDateString())}</td>
        <td>#${r.prNumber}</td>
        <td>${r.filesReviewed}</td>
        <td>${r.findingsCount}</td>
        <td class="severity critical">-</td>
        <td class="severity major">-</td>
        <td class="severity minor">-</td>
        <td>$${r.costUsd.toFixed(4)}</td>
        <td>${r.durationSeconds.toFixed(1)}s</td>
        <td>${r.cacheHit ? '✅' : '❌'}</td>
      </tr>
    `
      )
      .join('');

    return `
    <div class="table-container">
      <h2>📋 Recent Reviews</h2>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>PR</th>
            <th>Files</th>
            <th>Findings</th>
            <th>Critical</th>
            <th>Major</th>
            <th>Minor</th>
            <th>Cost</th>
            <th>Duration</th>
            <th>Cache</th>
          </tr>
        </thead>
        <tbody>
          ${rows || '<tr><td colspan="10">No reviews yet</td></tr>'}
        </tbody>
      </table>
    </div>`;
  }

  /**
   * Get CSS styles
   */
  private getCSS(): string {
    return `
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f7fa; color: #2c3e50; line-height: 1.6; }
      .container { max-width: 1400px; margin: 0 auto; padding: 20px; }
      header { text-align: center; margin-bottom: 40px; padding: 40px 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 10px; }
      header h1 { font-size: 2.5em; margin-bottom: 10px; }
      .subtitle { opacity: 0.9; font-size: 0.9em; }
      .summary-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; }
      .card { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); display: flex; align-items: center; gap: 15px; }
      .card.highlight { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; }
      .card-icon { font-size: 2em; }
      .card-content h3 { font-size: 0.9em; opacity: 0.8; margin-bottom: 5px; }
      .card-value { font-size: 1.8em; font-weight: bold; }
      .card-subtitle { font-size: 0.8em; opacity: 0.9; margin-top: 5px; }
      .charts-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(500px, 1fr)); gap: 30px; margin-bottom: 40px; }
      .chart-container { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
      .chart-container h2 { margin-bottom: 20px; font-size: 1.3em; }
      .chart-note { text-align: center; font-size: 0.85em; opacity: 0.6; margin-top: 10px; }
      .roi-section { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin-bottom: 40px; }
      .roi-section h2 { margin-bottom: 20px; font-size: 1.3em; }
      .roi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; }
      .roi-item { padding: 20px; background: #f8f9fa; border-radius: 8px; }
      .roi-item.highlight { background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%); }
      .roi-item h3 { font-size: 0.9em; opacity: 0.8; margin-bottom: 10px; }
      .roi-value { font-size: 2em; font-weight: bold; margin-bottom: 5px; }
      .roi-desc { font-size: 0.85em; opacity: 0.7; }
      .table-container { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin-bottom: 40px; overflow-x: auto; }
      .table-container h2 { margin-bottom: 20px; font-size: 1.3em; }
      table { width: 100%; border-collapse: collapse; }
      th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }
      th { background: #f8f9fa; font-weight: 600; }
      tr:hover { background: #f8f9fa; }
      .severity { font-weight: bold; }
      .severity.critical { color: #e74c3c; }
      .severity.major { color: #f39c12; }
      .severity.minor { color: #3498db; }
      footer { text-align: center; padding: 40px 20px; opacity: 0.6; font-size: 0.9em; }
      footer a { color: #667eea; text-decoration: none; }
      @media (max-width: 768px) { .charts-grid { grid-template-columns: 1fr; } .summary-cards { grid-template-columns: 1fr; } }
    `;
  }

  /**
   * Get Chart.js JavaScript
   * Note: JSON.stringify() provides XSS protection by properly escaping strings for JavaScript context
   */
  private getChartJS(costTrends: CostTrend[], perfTrends: PerformanceTrend[], stats: MetricsData): string {
    const recent = stats.reviews.slice(-100);
    // Placeholder values - severity breakdown not currently tracked in ReviewMetric
    const critical = 0;
    const major = 0;
    const minor = 0;

    // Placeholder values - provider success/failure not currently tracked per review
    const totalSuccess = recent.reduce((sum: number, r: ReviewMetric) => sum + r.providersUsed, 0);
    const totalFailed = 0;

    return `
      // Cost Trend Chart
      new Chart(document.getElementById('costTrendChart'), {
        type: 'line',
        data: {
          labels: ${JSON.stringify(costTrends.map((t) => t.date))},
          datasets: [{
            label: 'Daily Cost (USD)',
            data: ${JSON.stringify(costTrends.map((t) => t.cost))},
            borderColor: '#667eea',
            backgroundColor: 'rgba(102, 126, 234, 0.1)',
            tension: 0.4,
            fill: true
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: { y: { beginAtZero: true, ticks: { callback: value => '$' + value.toFixed(2) } } }
        }
      });

      // Performance Trend Chart
      new Chart(document.getElementById('perfTrendChart'), {
        type: 'line',
        data: {
          labels: ${JSON.stringify(perfTrends.map((t) => t.date))},
          datasets: [{
            label: 'Avg Duration (seconds)',
            data: ${JSON.stringify(perfTrends.map((t) => t.avgDuration))},
            borderColor: '#f5576c',
            backgroundColor: 'rgba(245, 87, 108, 0.1)',
            tension: 0.4,
            fill: true
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: { y: { beginAtZero: true, ticks: { callback: value => value + 's' } } }
        }
      });

      // Findings Distribution Chart
      new Chart(document.getElementById('findingsChart'), {
        type: 'doughnut',
        data: {
          labels: ['Critical', 'Major', 'Minor'],
          datasets: [{
            data: [${critical}, ${major}, ${minor}],
            backgroundColor: ['#e74c3c', '#f39c12', '#3498db']
          }]
        },
        options: { responsive: true, plugins: { legend: { position: 'bottom' } } }
      });

      // Provider Success Chart
      new Chart(document.getElementById('providerChart'), {
        type: 'pie',
        data: {
          labels: ['Success', 'Failed'],
          datasets: [{
            data: [${totalSuccess}, ${totalFailed}],
            backgroundColor: ['#2ecc71', '#e74c3c']
          }]
        },
        options: { responsive: true, plugins: { legend: { position: 'bottom' } } }
      });
    `;
  }
}
